# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---
/**:
    ros__parameters:
        general:
            grab_resolution: 'HD2K' # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
            grab_frame_rate: 15 # ZED SDK internal grabbing rate
            
            # camera_timeout_sec: 5
            # camera_max_reconnect: 5
            # camera_flip: false
            # serial_number: 0 # usually overwritten by launch file
            # pub_resolution: "NATIVE" # The resolution used for output. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
            # pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
            # pub_frame_rate: 30.0 # frequency of publishing of visual images and depth images
            # gpu_id: -1
            # optional_opencv_calibration_file: "" # Optional path where the ZED SDK can find a file containing the calibration information of the camera computed by OpenCV. Read the ZED SDK documentation for more information: https://www.stereolabs.com/docs/api/structsl_1_1InitParameters.html#a9eab2753374ef3baec1d31960859ba19

        depth:
            min_depth: 0.1 # Min: 0.1, Max: 3.0
            max_depth: 3.0 # Max: 20.0
            
            # depth_mode: "NEURAL_PLUS" # Matches the ZED SDK setting: 'NONE', 'PERFORMANCE', 'QUALITY', 'ULTRA', 'NEURAL', 'NEURAL_PLUS' - Note: if 'NONE' all the modules that requires depth extraction are disabled by default (Pos. Tracking, Obj. Detection, Mapping, ...)
            # depth_stabilization: 1 # Forces positional tracking to start if major than 0 - Range: [0,100]
            # openni_depth_mode: false # 'false': 32bit float [meters], 'true': 16bit unsigned int [millimeters]
            # point_cloud_freq: 10.0 # [DYNAMIC] - frequency of the pointcloud publishing (equal or less to `grab_frame_rate` value)
            # depth_confidence: 50 # [DYNAMIC]
            # depth_texture_conf: 100 # [DYNAMIC]
            # remove_saturated_areas: true # [DYNAMIC]

        pos_tracking:
            pos_tracking_enabled: false # True to enable positional tracking from start


        # debug:
        #     sdk_verbose: 1 # Set the verbose level of the ZED SDK
        #     debug_common: false
        #     debug_sim: false
        #     debug_video_depth: false
        #     debug_camera_controls: false
        #     debug_point_cloud: false
        #     debug_positional_tracking: false
        #     debug_gnss: false
        #     debug_sensors: false
        #     debug_mapping: false
        #     debug_terrain_mapping: false
        #     debug_object_detection: false
        #     debug_body_tracking: false
        #     debug_roi: false
        #     debug_streaming: false
        #     debug_advanced: false
